# Generated by Django 5.1.3 on 2024-11-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='user',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='system_prompt',
            field=models.TextField(blank=True),
        ),
    ]
